site_name: Good Practice Guidelines
site_description: The Good Practice Guidelines for GP electronic patient records

theme:
  name: material
  features:
    - navigation.instant
    #  - navigation.tabs
    - navigation.tracking
    - navigation.top
    #  - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  font:
    text: Montserrat
    code: Roboto Mono

  favicon: assets/dynamic-child-favicon.png
  logo: assets/logo-desktop.svg

plugins:
  - search

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

copyright: Copyright RCGP, BMA and HSCIC
repo_url: https://github.com/pacharanero/the-good-practice-guidelines-for-gp-electronic-patient-records

extra_css:
  - stylesheets/extra.css
